# Generated by Django 4.2.4 on 2023-11-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alta_de_productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=50)),
                ('existencias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='alta_productos',
        ),
    ]
