# Generated by Django 4.2.4 on 2023-11-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0002_alta_de_productos_delete_alta_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('folio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altas.alta_de_productos')),
            ],
            options={
                'unique_together': {('folio', 'producto')},
            },
        ),
    ]
