# Generated by Django 4.2.4 on 2023-11-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0004_pago_productos_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('folio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altas.alta_de_productos')),
            ],
            options={
                'unique_together': {('folio', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='pago_productos',
        ),
    ]
