# Generated by Django 4.2.4 on 2023-12-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0005_pago_delete_pago_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago_articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.BigIntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altas.alta_de_productos')),
            ],
            options={
                'unique_together': {('folio', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='pago',
        ),
    ]
