# Generated by Django 4.2.4 on 2023-12-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0006_pago_articulos_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('serial', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.BigIntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altas.alta_de_productos')),
            ],
            options={
                'unique_together': {('serial', 'folio', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='pago_articulos',
        ),
    ]
