# Generated by Django 4.2.4 on 2023-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0009_pago_delete_pago_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta_de_productos',
            name='imagen_producto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
