# Generated by Django 4.2.4 on 2023-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0010_alta_de_productos_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
